import datetime
import json
import hashlib
import base64



class Blockchain:
    def __init__(self):
        self.chain = []
        genimg="/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAAAAAAAAAAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCANwA3ADASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAECA//EACUQAQEAAgICAwACAwEBAAAAAAABETECEkFhIVFxgZGh0fCx4f/EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/xAAbEQEBAQEBAQEBAAAAAAAAAAAAARExIUECUf/aAAwDAQACEQMRAD8A6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAKIAogCiAKIAogCiAKIAogCiAKIAogCiAKIAogCiAKIAogCiAKIAogCiAKIAogCiAKIAogCiAKIAogCiAKIAogCiAKIAogCiAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAioAmS6ZBrJlkBrJlkBrJlkBrJlkBrJlkBrJlkBrJlkBrJlkBrJlkBrJlkBrJlkBrJlkBrJlkBrJlkBrJlP1O30DWTtHPOdoYOvafado5hg6dp7XtHIMHXM+4riGDrbZ4Tt6Z7WeV7S7hi6vb0dvSYl1f4TGEXxrt6O3pkDGu3o7emQMa7ejt6ZAxrt6O3pkDGu3o7emQMa7ejt6ZAxrt6O3pkDGu3o7emQMa7ejt6ZAxrt6O3pkDGu3o7emQMa7ejt6ZAxrt6O3pkDGu3o7emQMjXb01Plzb46EsaAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFQC6YbumCAAIAAAAAAAAAAAAAAAAAAAAAAAAJn6S3KAAKAAAAAAAAAADU5Xz8xkRW8S/M/pEazn1f/RZUARoAAAAAAAAAAAAAAAAAAAAAAAAb46Yb46ErQCsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKgF0w3dMEAAQAAAAAAAAAAAAAAAAAAAAAAS3wrAACgAAAAAAAAAAqKiwwjSC2IArLUufjz4oyqNSqAjQAAAAAAAAAAAAAAAAAAAAAA3x0w3x0JWgFZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEVALphu6YIAAgAAAAAAAAAAAAAAAAAAAAACVlaigAAAAAAAAAAAA0yqLLhkQDaAKgADQkVluAAoAAAAAAAAAAAAAAAAAAAA3x0w3x0JWgFZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEVALphu6YIAAgAAAAAAAAAAAAAAAAAAAABdAwAoAAAAAAAAAAAAAAAAAAAAsVFStwARQAAAAAAAAAAAAAAAAAAABvjphvjoStAKyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIqAXTDd0wQABAAAAAAAAAAAAAAAAAAAABLpUoMgKANdagyNdayAAoAAAsloIOnWL1iarkOnWM3jgGQFQAAAAaZaStfkARoAAAAAAAAAAAAAAAAAAAAb46Yb46ErQCsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBdMN3TBAAEAAAAAAAAAAAAAAAAAAAAEqpQZBrjv8BqccfrQmZPMRVZsaAckarLSAALJm4ddMcJutpVAEAAGOUYdq5XaiAKgAAqLErU6oCNAAAAAAAAAAAAAAAAAAAADfHTDfHQlVUVWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFQC6YbumCAAIAAAAAAAAAAAAAAAAAAAAJVS6BlvhusN8PIpyvj+2ZM3C8t1kHbU/CXPynG5icfi2IJyYdOTmoAKjrx1FTjqfhy1/hlWLc/hxsl+WRR2GON+cNcrifygrnydGOXlYMAKgAAsRYizqgI2AAAAAAAAAAAAAAAAAAAAN8dMN8dCVVRVZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEVAS6ZaumSAAIAAAAAAAAAAAAAAAAAAAAF0F0DDfDd/GFlxYK1znlh2sz8OdlgHG4yS/Of1GpMAX5ZxWzFBhHTFAOOjnqfqF+YDACoq25Za4z5/PlFdGeXn8aY5eUgwA0gAAsRYizqgI2AAAAAAAAAAAAAAAAAAAAN8dMNzQlVUVWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFQEumWrpkgACAAAAAAAAAAAAAAAAAAAABdULqgwAo6ceXx8s8rm4iSZaRSTDUjLYACAABiJhQGbxz/tnrXQXRzwnzK6YiWfyCd79M25WxkABUAAFiKixQEbAAAAAAAAAAAAAAAAAAAAG5phuaEqqiqyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIqAl0y1dMkAAQAAAAAAAAAAAAAAAAAAAAABhZMo1FFAQWbaSKigAAAAAAAAZZvIGsZc7G4nJRzAVAAAAGhFZdAAAAAAAAAAAAAAAAAAAABuaYbmhKqoqsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKgJdMtXTJAAEAAAAAAAAAAAAAAAAAAAAAAYAUal+1YWVB1ElVFAAAzEyCjPZnNq4N5iXkzi3danEGc26jU4+a18Rm0Ft+nOqgt8iAKyAAAAqsqlalUBGgAAAAAAAAAAAAAAAAABuaYb46EqqiqyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIqAl0y1dMkAAQAAAAAAAAAAAAAAAAAAAAABlFRQFxhAXNMrMLiIrOTLXVev4DGaYt/8Arp1MQGJP5aw1mJkF+ImWLf5T5oLaiziuMAjLdZot9iAKyAAAAKgitCKjYAAAAAAAAAAAAAAAAAA3x0w3x0JVVFVkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARQGbplq6ZIAAgAAAAAAAAAAAAAAAAAAAAlqsgizaN8YC2fDDqxygrDUv2yKja5rmuag3moygNZibJMtziKzONvpuSRRASxQGErSKRgVAsAFQAAABVZWI1KoCNAAAAAAAAAAAAAAAADfHTDfHQlVUVWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGbplq6ZIAAgAAAAAAAAAAAAAAAAAACW+AS3KAoO0mIxxnltKoUEHOxl1sYsUZFxTFVEWTKzi6SYRUkwoIAAAAIipVGalaQXsZAVkAAAAABVRUblAEUAAAAAAAAAAAAAAb46YbmhK0ArIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADN0y1dMkAAQAAAAAAAAAAAAAAAAAAtwwqKCo1AbmlJoZUAAMACYMKAAAAAAAFEASqiiIpRYzUVBL0AVAAAABYgitCKjYAAAAAAAAAAAAAA3NMNzQlaAVkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABm6ZaumSAAIAAAAAAAAAAAAAAAAM25W3wyAAoNsNoNzQzGkUAAAAAAAAAAAAqAoMqgBQoTqMtIRagCsgKi4gCoAANMqjUqgI0AAAAAAAAAAAANzTDc0JWgFZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZumWrpkgACAAAAAAAAAAAAAABaMggCgAA2w2gNxhqCqAgAAAAAAAAlqKKIjSAgAgAKiVaI12MgNMioIKilFvvqAKyAAqsrErUqgI0AAAAAAAAAANzTDc0JWgFZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZumWrpkgACAAAAAAAAAAAAAAJfpkFAAAFBZPKiyIo0CAAAAAAAAAABWWkoIB/2lEFQQAARSjUrKNIQsQBWRplYjUojTIlgAqAArQkVlqAAoAAAAAAAA3NMNzQlaAVkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAS6ZaumSAAIAAAAAAAAAAAAJVZoIAoAANRHSTERSRQQAAAAAAAAAAAACgDIooiNICACAAqAI2yLUVgAVGkpFRvsZAVgAAaZWJWooCNAAAAAAAADc0w3NCVoBWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAZumWrpkgACAAAAAAAAAAAAF0w1WVAAAAVvjG0kxFZUAEAAAAAAAAAAAAAAKioAlVFEAEAAKi1EbiVGmViUAVkaZWJWoItQS9AFQVAVoSKy2AAAAAAAANzTDc0JWgFZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZumWrpkgACAAAAAAAAAAAJQZAUAAFm0b4+EWNgIAAAAAAAAAAAAAAAACKlAEFBFQAAQRUK1BFSkWoArAsRUWdEaZItAFZAAWKipW4AIoAAAAAA3NMNzQlaAVkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABm6ZaumSAAIAAAAAAAAAAMrfpkBUWixAFRWuLMbnhF+NAIAAAAAAAAAAAAAAAACVUoACiVFQAAQSqlGp0SqlFvEAVgARWmWmSLQBWQABplUrUUBGgAAAAABuaYbmhK0ArIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADN0y1dMkAAQAAAAAAAABmggCilCo18QBWVjc8MRueEa+NAIgAAAAAAAAAAAAAAAAlVKAAoiKgAAglVKLOiVUpGrxAFYFRYiwqLUC9AFQAAWIsRZ1QEbAAAAAAG5phuaErQCsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM3TLV0yQABAAAAAAAABhu6YAAUFqKjUQBUWNTwzGkX5GwEQAAAAAAAAAAAAAAAASqgACiItQAAQSqlGp0SqiLeIArIsMKLIiKglAFQAAVFRYoCNgAAAAADc0w3NCVoBWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGbplq6ZIAAgAAAAAAABdMN3TAACgsQRVRVFzUjSLAs8bmhIqIAAAAAAAAAAAAAAAAIUAAUSoqAACCKg1AERpUygrOrkygJtXIgLqoAgAqCosRYoCNgAAAAADc0w3NCVoBWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGbplq6ZIAAgAAAAAAAAmGgVBrBgGMI3hLMiMKILLjQio11qNMRqVWVAQAAAAAAAAAAAAASggCgACACAJRZ6CINbjSGKgzboAqAAAAAAAACipWpABGgAAAAABuaYbmhK0ArIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADN0y1dMkAAQAAAAAABKBLdNxiOhVAEBLFAYsYdbGbFGFQBpWVF63KrCyiNAIAAAAAAAAAJkAQUUQAQAABBFqDcRZPLLYyJftvBYDkKioAAAAAALJkkaQMJhQWVAEbAAAAAAG5phuaErQCsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM3TLV0yQABAFwCC49z+zHuCoL/M/tMz7z+AM0tyT5Ea4+G0ipVAAAAEs8qA52eWXSxizCogCq0uWFRetrn7YUTMbGFyYNCCC5MoAZPkFEFAQABAEAAAAKi1EbnE8/y3NsTcdIrKgIM8pn5c3Zm8fMUcxcVFQFMAjUn2sn01IipI0CBdOdbumKsEipFRqcABQAAABuaYbmhK0ArIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADN0y1dMkAARLUxkrQM9TFbxVwK54v0Yv03imKDOFXFXAE0oIAAAAAAFYbZqwYRqxlUAAVWVRqVrIihZ/FMoCKIAogC5EAABAAAAAAVKAjaTf8ukcnWKwoCAABhMKAmFxAAAAABLpit3TF0sDj5n3r9GW9zPmbFlQBGgAAABuaYbmhK0ArIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADN0y1dMkAARhueGasB0EiooAAAAAAAAAAAAUAYZsbsRRgVFQAAaZWJWo1BFCwAGQAAAAAAAAAUQEakwAFZb4+GGorDoAgAAAAAAAAAAMNpYDmS4WzLKo3v5m/MRGsy7+L9jUqBZgRoAAbmmG5oStAKyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzdMtXTJAAESstXTKjpL/lpzjolUAQAAAAAAAAAAAAGWksyDNmWG0s8qjICgsFRqQVFCgAyAAAAAAAmRZFygI1JgCBbijLSkustRlYMuoCAAAAAAAAAAAACYSxoBzwmK6pj6XRiWz8+l+L8z+jDOg1RFRsbmmG5oSqqKrIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADN0y1dMkAAQumGrplRqeXSac46TSVQBAAAAAAAAAAAAAABLPLLbNijAtiBFARsXKAmaogupiiAYogaYqZBFwAFAQTRAVm3RpFKsZWbRZsR1AQAAAAAAAAAAAAAAALQSsVq1i/KhFRUanBuaYbmgqqiqyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzdMtXTJAAESsjUgLJ4bJMCKAAAAAAAAAAAAAAAAAAzpiulYqiCNCz1lSoHGhDJi6omTKGxRMmQ2KJkXDVTKBiaqAqAAiwCo38RrjtlviMtgIAAAAAAAAAAAmYZBTLFvtMrg1lMxnNMB02KDUgAijc0w3NCVVRVZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEVAS6Zauq55pBoumc0yITbbm1kHQYnJrKKoZgAAAAAAAAAAAAAAAABdVzunS6YulgwsQCNMtMkWgCsgAAAAAAAAAAArSVUqNXiOnHTm68dFZUBAAAAAAABm3+gXLNv2lv0yo1lEFQXAZRZiiZMjWxRMmQ2KJkyGxW5pzy6cdREtVUVUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEVATlquTry1XIgAKgAAAC5q5ZAb7fq5cxFdcmY5maYOo55XPswbEyZiCgAAAAAAAlYrTFUQBUWoCKAKgAAAAAAAAAAAC5QEXR046c1lxQdQEAAAAAGLy+gLWdoKgAoAAAAAAAAAAOvHUcnXjqJVVUUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFQE5ark68tVyIACoAAAAAAAAAAAALmoA1n0vb2wIOmfxrLiuaYrrmGY5Zpm+jB0yjGaZBbWQVAAAAAAAAAAAAAAAAAAAAAAGpcfjcsunIRXYc+1+ztf+hg6JeUjnm3yhgttv8ApAEAFAAAAAAAAAAAAB146jk68dRKqqigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIqAnLVcnXlquRAAVAAAAAAAGp5BkbEGBqsqAAAAAKANCDA3dMKAKANCDA2lijIAALNgDQgwNVlQBqAg0IMDVZUAABqKDKNpfCDILPhQGhBgbZUQAAGpAQaEGBqsqAAAAAADrx1HJ146iVVVFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABATlquTry1XIgAKgAAAAAA1PLLUBQEErLVZUAAAAFm0WbBoBAuqw3dMALNxFnhRoBAABlGr9sqCxFgNAIJWWqyoNRlqAoCCVlqsqAANRUioCXwqXwDICjUvhWG58oCWKAwLYiiz5aJMCADNoCAoAAAAAAOvHUcnXjqJVVUUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFQE5ark68tVyIACoAAAAAANRlqAoCCVlqsqAAAACzaLAaAQLphu6YAWbRVGgEAKAMtJfsGVm0WKNAIJWWqyoNTTLU0CgIM1Fu0UAAaipFQEqpQZAUFlwgDYkqoCSKAAAWsLflFAAAAAAAAB146jk68dRKqqigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIqAnLVcnXlquRAAVAAAAAABqMtQFAQSstVlQAAAAWIsBoBAumG7pgBUVRoBBLon0t0wDYAMLFv2kUaAQSstVlQammWpoFAQZu0W7RQABqKkVASql8AyAoAANsNzSAAAlvhWbsEAUAAAAAAAAHXjqOTrx1EqqqKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAioCctVydeWq5EABUAAAAAAGoy1AUBBKy1WVAAAABYizYNAIF0w3dMAKiqNAIF0w3dMA1PpWGwEm1AAASstVlQajLU8goCCVlqsqAANRUioCXwqXwDICgCgSNAgAS5AL8gDA1Z5ZUAAAAAAAAHXjqOTrx1EqqqKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAioCctVydeWq5EABUAAAAAAGoy1AUBBKy2Yn0DA3iGIowN4iYgMrNos2DQCBdMN3VYAVFUaAQLphu6YAan0yqjQCAACVlqsqCxFBoBArDaYBkax7XChAEBm7aYAAUGpEkaQAAS3wiCjYkqoDN+GizIMAKAAAAAADrx1HJ146iVVVFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARUBOWq5OvLVciAAqAAAAAADUZWfANBmGYgBmGYAGYZgAZiZgMrEFGxMxcxAumGrWQFQUbDMMxAumGrWVAAGp9Kw1lBQzDMBKytuUUAAalVhZUGgzAAAATMS3IFuUBQBYDU+AzDMQGbVt+mQAFBuXLCg0JmLmIM2I1mMqAAAAAADrx1HJ146iVVVFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARUBOWq5O1mfhnpPYOY6dYdZ7NHMdOs9nSGjmOnWezrPZo5jp1ns6z2aOY6dYdJ7NHMdOsOsNHMdOs9nWezRzHTrPZ1ns0cx06z2dJ7NHMdOs9nWezRzHTrDrDRzHTrPZ1ho5jp1h1ho5jp1h1ho5jp1h1ho5jp1h1ho5jp1h1ho5jp1h1ho5jp1h1ho5jp1h0ho5jp1h1ho5jp1h1howjp1h1ho5jp1h1ho5jp1h1ho5jp1h1ho5jp1ns6z2aOY6dZ7Os9mjmOnWezrPZo5jp1h0ns0cx06z2dZ7NHMdOk9nWezRzHTrPZ1ns0cx06w6Q0cx06z2dYaObrx1E6xqTHwAqKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCgIKAgoCCgIKAgoCCgIKAgoCCgIKAgoCCgIKAgoCCgIKAgoCCgIKAgoCCgIKAgoCCgIKAgoCCgIKAgoCCgIKAgoCCgIKAgoCCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/9k="
        self.create_blockchain(proof=1, previous_hash='0',img=genimg)

    def create_blockchain(self, proof, previous_hash,img):
        block = {
            'index': len(self.chain) + 1,
            'timestamp': str(datetime.datetime.now()),
            'image': img ,
            'proof': proof,
            'previous_hash': previous_hash
        }

        self.chain.append(block)
        return block

    def get_previous_block(self):
        last_block = self.chain[-1]
        return last_block

    def proof_of_work(self, previous_proof):
        # miners proof submitted
        new_proof = 1
        # status of proof of work
        check_proof = False
        while check_proof is False:
            # problem and algorithm based off the previous proof and new proof
            hash_operation = hashlib.sha256(str(new_proof ** 2 - previous_proof ** 2).encode()).hexdigest()
            # check miners solution to problem, by using miners proof in cryptographic encryption
            # if miners proof results in 4 leading zero's in the hash operation, then:
            if hash_operation[:4] == '0000':
                check_proof = True
            else:
                # if miners solution is wrong, give mine another chance until correct
                new_proof += 1
        return new_proof

    # generate a hash of an entire block
    def hash(self, block):
        nblock=dict.copy(block)
        nblock.pop('image')
        encoded_block = json.dumps(nblock, sort_keys=True).encode()
        return hashlib.sha256(encoded_block).hexdigest()

    # check if the blockchain is valid
    def is_chain_valid(self, chain):
        # get the first block in the chain and it serves as the previous block
        previous_block = chain[0]
        # an index of the blocks in the chain for iteration
        block_index = 1
        while block_index < len(chain):
            # get the current block
            block = chain[block_index]
            # check if the current block link to previous block has is the same as the hash of the previous block
            if block["previous_hash"] != self.hash(previous_block):
                return False

            # get the previous proof from the previous block
            previous_proof = previous_block['proof']

            # get the current proof from the current block
            current_proof = block['proof']

            # run the proof data through the algorithm
            hash_operation = hashlib.sha256(str(current_proof ** 2 - previous_proof ** 2).encode()).hexdigest()
            # check if hash operation is invalid
            if hash_operation[:4] != '0000':
                return False
            # set the previous block to the current block after running validation on current block
            previous_block = block
            block_index += 1
        return True
    def replacechain(self,blocks):
        if len(blocks) <= len(self.chain):
            return
        elif not self.is_chain_valid(blocks):
            return
        self.chain=blocks
        return

class imageHandeling:
    def __init__(self):
        #initializing image path
        self.img="\img.jpg"

    def encode_string(self):
        with open(self.img, "rb") as image:
            image_string = base64.b64encode(image.read())
        return image_string.decode("ascii")

class readData:
    def __init__(self):
        self.gg=None
    def retrive(self):
        self.gg=[]
        with open("templates/response.json",'r') as fp:
            data=json.loads(fp.read())
            for dt in data["chain"]:
                self.gg.append(dt)
        return self.gg

 